# .github/workflows/pr-title-check.yml
name: PR Title Check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [production]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title format (vMAJOR.MINOR.PATCH#ticket)
        shell: bash
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          if [[ "$TITLE" =~ ^v[0-9]+\.[0-9]+\.[0-9]+#.+$ ]]; then
            echo "OK: $TITLE"
          else
            echo "::error title=Invalid PR title::Require vMAJOR.MINOR.PATCH#ticket (e.g., v1.2.3#ABC-123)"
            exit 1
          fi
